### ISSUE TITLE
[bug] User annotations error in expansion

### ISSUE THREAD

**Issue by samdphillips** [racket/rhombus-prototype#217]
After f21679842c56b0841b156dde6b389e0366f15532 this program errors during expansion.

```
#lang rhombus

import:
  rhombus/macro open
  racket/base

annotation.macro 'N':
  annotation_ct.pack_predicate('base.#{number?}')

val a :: N : 42
a
```

```
result arity mismatch;
 expected number of values not received
  expected: 2
  received: 1
  in: local-binding form
  arguments...:
   #<syntax:/home/sam/projects/contrib/rhombus-prototype/rhombus/private/annotation-syntax.rkt:78:4 (parsed ((rhombus-expression (group base (op |.|) number?)) ()))>
  context...:
   /home/sam/projects/contrib/rhombus-prototype/enforest/operator.rkt:192:3
   /home/sam/projects/contrib/rhombus-prototype/enforest/main.rkt:218:8: dispatch-prefix-operator
   .../private/parse.rkt:559:26
   /home/sam/projects/contrib/rhombus-prototype/enforest/operator.rkt:202:3
   /home/sam/projects/contrib/rhombus-prototype/enforest/main.rkt:276:8: dispatch-infix-operator
   /home/sam/projects/contrib/rhombus-prototype/enforest/main.rkt:154:2
   .../private/parse.rkt:162:7: parse-:binding7
   /home/sam/projects/contrib/rhombus-prototype/enforest/transformer.rkt:70:3
   .../private/parse.rkt:559:26
   .../private/runtime.rkt:82:34: fail-handler595
   /home/sam/projects/contrib/rhombus-prototype/rhombus/private/srcloc.rkt:88:3
   .../private/runtime.rkt:80:24: temp113
   /usr/local/stow/racket-8.4.0.8-20220323-e2a6b25/share/racket-8.4.0.8/collects/syntax/wrap-modbeg.rkt:46:4
```

The equivalent program before this version runs:
```
#lang rhombus

import:
  rhombus/macro open
  racket/base

annotation.macro 'N:
  annotation_ct.pack_predicate('(base.#{number?}))

val a :: N : 42
a
```

**Comment by mflatt** [comment]
This was an intentional change, although I didn't think to advertise it better. (Also, documentation is still lacking in this area.)

Previously, there could be a syntactic distinction between `'N` for a just identifier and `'(N)` for a 0-argument pattern, and that distinction could trigger different `annotation.macro` protocols. But now that `()` is not required to quote multi-term forms, the shorthand-enabling distinction went away. Now, `annotation.macro` always uses a protocol that expects two results.

Partly to compensate, I added `annotation.rule`. That's analogous to `expr.rule`, and it similarly works only for simple cases. It doesn't help here.

**Comment by samdphillips** [comment]
I see.  I was using the documentation as authoritative on this since I thought you had updated it with the new syntax.

> Partly to compensate, I added annotation.rule. That's analogous to expr.rule, and it similarly works only for simple cases. It doesn't help here.

I was under the impression that the `*.rule` forms were the same as `syntax-rules` in that they only allow a template on the right-hand side and not procedural macros (like `annotation_ct.pack_predicate`)
