### ISSUE TITLE
matching(_) on rhs of (||) in annotations with default values causes parsing errors

### ISSUE THREAD

**Issue by laelath** [racket/rhombus-prototype#364]
Example:
```rhombus
fun f1(x :: matching(#false) || Int = 42): x   // works
fun f2(x :: Int || matching(#false) = 42): x   // doesn't work
fun f3(x :: (Int || matching(#false)) = 42): x // works again
```

I'm not sure if this is intended/acceptable behavior or not, but the produced error message is fairly unhelpful.
```
parens: misplaced binding;
 no infix operator is between this binding and the previous one
  in: (#false)
```

**Comment by usaoc** [comment]
A minimal example reveals the actual problem:

```
#lang rhombus/static
def _ :: Int || matching(#false):
  #false
// parens: misplaced binding; ....

def _ :: Int || matching:
  #false
// this works!
```

The problem is that `||` is both a binding and annotation operator, so the binding `||` takes over.  If you observe more carefully, `x :: matching(#false) || Int` behaves like `(x :: matching(#false)) || Int` (so nothing is bound at all, and `Int` is treated as a *pattern* that matches anything), and similarly `x :: Int || matching` like `(x :: Int) || matching` (again, `matching` is a *pattern*).  This leaves the `(#false)` alone, which triggers the parsing error.

**Comment by usaoc** [comment]
Just for the record, here’s a rough description of how the parsing proceeds:

- The enforestation starts with `x :: Int || matching(#false)`;
- `::` is encountered;
- `||` is encountered; the *binding* operator `::` is weaker than `||`; the transformer is called with `:: Int || matching(#false)` as the tail;
- The transformer switches to parse in annotation context;
- `::` is encountered;
- `||` is encountered; the *annotation* operator `::` (not exported!) is stronger than `||`; the transformer is called with `:: Int` as the tail;
- The transformer returns the parsed result of `x :: Int`; the enforestation continues in binding context;
- …
- `(#false)` is left alone as the tail—error!

The tricky part is how `::` switches the context in an unusual way.
