### ISSUE TITLE
Surprising behavior of literal bindings when `case` expansion applies

### ISSUE THREAD

**Issue by usaoc** [racket/rhombus-prototype#417]
Racket `case` follows `equal?` semantics, while Rhombus wants `equal-always?` semantics.  This leads to some corner cases being broken:

```
#lang rhombus/static
import:
  lib("racket/base.rkt").#{string-copy}

match #{string-copy}("abc")
| "abc": "matched"
| ~else: "unmatched"
```

(And I realized there was another bug that broke the `case` expansion when all patterns are literal.  Welp, let’s fix that first.)

Should we add different versions of `case` to Racket?  I’m not sure how I feel about that.

**Comment by AlexKnauth** [comment]
I'd lean towards an optional keyword.
Would a syntax parameter ever accidentally apply to situations where someone wants the normal equal-case behavior inside a clause of another case expression overridden for a different equality?

**Comment by usaoc** [comment]
`eq?`, `eqv?`, `equal?`, and `equal-always?` are all that apply to `case`, right?  (It can’t be an arbitrary procedure due to the dispatch algorithm used.)  I’m not sure having an optional directive that recognizes *exactly those* identifiers is a better idea than having different versions of `case` altogether.

**Comment by mflatt** [comment]
Maybe add a new `case` variant to Racket, but in a `racket/case` (or `racket/case-always`) module instead of `racket/base` or `racket`?

**Comment by samth** [comment]
A new case variant seems like it would either require duplication of the `case` implementation or internally providing a dispatched variant from the implementation in `racket/private/case.rkt`.

**Comment by rocketnia** [comment]
> `eq?`, `eqv?`, `equal?`, and `equal-always?` are all that apply to `case`, right? (It can’t be an arbitrary procedure due to the dispatch algorithm used.)

I don't think it would need to be limited to those in principle, since it is possible to build custom hash tables, AVL trees, tries, range maps, etc. using arbitrary Racket code and [`syntax-local-lift-expression`](https://docs.racket-lang.org/reference/stxtrans.html#%28def._%28%28quote._~23~25kernel%29._syntax-local-lift-expression%29%29) their construction. Moreover, an internal data structure for this purpose could get even cleverer and represent itself strictly in terms of vectors and such just to get access to quotability if that's important.

Better than lifting or quoting might be to do a `define/match`-like design—a form for defining a function that immediately invokes `case` on one of its arguments—so that the programmer knows exactly what "definition time" the data structure construction is performed at and can reposition it to wherever in their code they like it. Having a well defined "definition time" would even open up the potential for non-constant expressions in branch conditions, since those expressions could be documented to run specifically at definition time and in the definition site's lexical scope.
